

DROP DATABASE quanlibanve

#DROP TABLE VaiTro
CREATE TABLE VaiTro (
	MaVaiTro VARCHAR(25) NOT NULL,
	TenVaiTro VARCHAR(25) NOT NULL,
	CONSTRAINT PK_VaiTro PRIMARY KEY (MaVaiTro),
	CONSTRAINT UC_VaiTro UNIQUE (MaVaiTro)
)

#DROP TABLE Quyen
CREATE TABLE Quyen (
	MaQuyen VARCHAR(25) NOT NULL,
	TenQuyen VARCHAR(25) NOT NULL,
	CONSTRAINT PK_Quyen PRIMARY KEY (MaQuyen),
	CONSTRAINT UC_Quyen UNIQUE (MaQuyen)
)

#DROP TABLE QuyenVaiTro
CREATE TABLE QuyenVaiTro (
	MaQuyen VARCHAR(25) NOT NULL,
	MaVaiTro VARCHAR(25) NOT NULL,
	CONSTRAINT PK_QuyenVaiTro PRIMARY KEY (MaQuyen, MaVaiTro),
	CONSTRAINT FK_QuyenVaiTro_Quyen FOREIGN KEY (MaQuyen) REFERENCES Quyen(MaQuyen),
	CONSTRAINT FK_QuyenVaiTro_VaiTro FOREIGN KEY (MaVaiTro) REFERENCES VaiTro(MaVaiTro)
)

#DROP TABLE NhanVien
CREATE TABLE NhanVien (
	MaNhanVien INT NOT NULL AUTO_INCREMENT,
	HoTen VARCHAR(100) NOT NULL,
	GioiTinh BOOL NOT NULL,
	SoDienThoai VARCHAR(11) NOT NULL,
	NgayDangKy DATE NOT NULL DEFAULT CURRENT_DATE(),
	NgaySinh DATE NOT NULL,
	TrangThai INT NOT NULL DEFAULT 1,
	MatKhau VARCHAR(100) NOT NULL,
	Email VARCHAR(50) NOT NULL,
	MaVaiTro VARCHAR(25) NOT NULL,
	CONSTRAINT PK_NhanVien PRIMARY KEY (MaNhanVien),
	CONSTRAINT FK_NhanVien_VaiTro FOREIGN KEY (MaVaiTro) REFERENCES VaiTro(MaVaiTro)
)

#DROP TABLE KhachHang
CREATE TABLE KhachHang (
	MaKhachHang INT NOT NULL AUTO_INCREMENT,
	HoTen VARCHAR(100) NOT NULL,
	SoDienThoai VARCHAR(11) NOT NULL,
	ThoiGianDangKy DATETIME NOT NULL DEFAULT CURRENT_TIME(),
	LaKhachHangThanThiet INT NOT NULL,
	CONSTRAINT PK_KhachHang PRIMARY KEY (MaKhachHang),
	CONSTRAINT UC_KhachHang UNIQUE (MaKhachHang, SoDienThoai)
)

#DROP TABLE Tau
CREATE TABLE Tau (
	MaTau VARCHAR(25) NOT NULL,
	TenTau VARCHAR(50) NOT NULL,
	CONSTRAINT PK_Tau PRIMARY KEY (MaTau)
)

#DROP TABLE ToaTau
CREATE TABLE ToaTau (
	MaToa VARCHAR(25) NOT NULL,
	TenToa VARCHAR(50) NOT NULL,
	MaTau VARCHAR(25) NOT NULL,
	CONSTRAINT PK_ToaTau PRIMARY KEY (MaToa),
	CONSTRAINT FK_ToaTau_Tau FOREIGN KEY (MaTau) REFERENCES Tau(MaTau)
)

#DROP TABLE Khoang
CREATE TABLE Khoang (
	MaKhoang VARCHAR(25) NOT NULL,
	TenKhoang VARCHAR(50) NOT NULL,
	MaToa VARCHAR(25) NOT NULL,
	CONSTRAINT PK_Khoang PRIMARY KEY (MaKhoang),
	CONSTRAINT FK_Khoang_ToaTau FOREIGN KEY (MaToa) REFERENCES ToaTau(MaToa)
)

#DROP TABLE Tuyen
CREATE TABLE Tuyen (
	MaTuyen VARCHAR(25) NOT NULL,
	DiemDi VARCHAR(50) NOT NULL,
	DiemDen VARCHAR(50) NOT NULL,
	NgayTaoTuyen DATE NOT NULL,
	CONSTRAINT PK_Tuyen PRIMARY KEY (MaTuyen)
)

#DROP TABLE Chuyen
CREATE TABLE Chuyen (
	MaChuyen VARCHAR(25) NOT NULL,
	ThoiGianKhoiHanh DATETIME NOT NULL,
	ThoiGianDen DATETIME NOT NULL,
	MaTuyen VARCHAR(25) NOT NULL,
	MaTau VARCHAR(25) NOT NULL,
	CONSTRAINT PK_Chuyen PRIMARY KEY (MaChuyen),
	CONSTRAINT FK_Chuyen_Tau FOREIGN KEY (MaTau) REFERENCES Tau(MaTau),
	CONSTRAINT FK_Chuyen_Tuyen FOREIGN KEY (MaTuyen) REFERENCES Tuyen(MaTuyen)
)

#DROP TABLE LoaiVe
CREATE TABLE LoaiVe (
	MaLoaiVe VARCHAR(25) NOT NULL,
	TenLoaiVe VARCHAR(50) NOT NULL,
	LoaiKhoang VARCHAR(25) NOT NULL,
	CONSTRAINT PK_LoaiVe PRIMARY KEY (MaLoaiVe)
)

#DROP TABLE Ve
CREATE TABLE Ve (
	MaVe VARCHAR(25) NOT NULL,
	ChoNgoi INT NOT NULL,
	GiaVe DOUBLE NOT NULL,
	MoTa VARCHAR(255) NULL,
	TinhTrangVe INT NOT NULL DEFAULT 1,
	MaLoaiVe VARCHAR(25) NOT NULL,
	MaChuyen VARCHAR(25) NOT NULL,
	CONSTRAINT PK_Ve PRIMARY KEY (MaVe),
	CONSTRAINT FK_Ve_LoaiVe FOREIGN KEY (MaLoaiVe) REFERENCES LoaiVe(MaLoaiVe),
	CONSTRAINT FK_Ve_Chuyen FOREIGN KEY (MaChuyen) REFERENCES Chuyen(MaChuyen)
)


CREATE TABLE KhuyenMai (
	MaKhuyenMai VARCHAR(50) NOT NULL,
	PhanTramGiamGia DOUBLE NOT NULL DEFAULT 0,
	GhiChu VARCHAR(255) NULL,
	ThoiGianBatDau DATETIME NOT NULL,
	ThoiGianKetThuc DATETIME NOT NULL,
	CONSTRAINT PK_KhuyenMai PRIMARY KEY (MaKhuyenMai)
)


CREATE TABLE HoaDon (
	MaHoaDon VARCHAR(25) NOT NULL,
	ThoiGianTaoHoaDon DATETIME NOT NULL DEFAULT CURRENT_TIME(),
	GhiChu VARCHAR(255) NULL,
	VAT DOUBLE NOT NULL,
	TienKhachDua INT NOT NULL,
	MaKhachHang INT NOT NULL,
	MaNhanVien INT NOT NULL,
	MaKhuyenMai VARCHAR(50) NULL,
	CONSTRAINT PK_HoaDon PRIMARY KEY (MaHoaDon),
	CONSTRAINT FK_HoaDon_KhachHang FOREIGN KEY (MaKhachHang) REFERENCES KhachHang(MaKhachHang),
	CONSTRAINT FK_HoaDon_NhanVien FOREIGN KEY (MaNhanVien) REFERENCES NhanVien(MaNhanVien),
	CONSTRAINT FK_HoaDon_KhuyenMai FOREIGN KEY (MaKhuyenMai) REFERENCES KhuyenMai(MaKhuyenMai)
)


CREATE TABLE ChiTietHoaDon (
	MaChiTietHoaDon INT NOT NULL AUTO_INCREMENT,
	DonGia DOUBLE NOT NULL,
	SoLuong INT NOT NULL DEFAULT 1,
	MaHoaDon VARCHAR(25) NOT NULL,
	MaVe VARCHAR(25) NOT NULL,
	CONSTRAINT PK_ChiTietHoaDon PRIMARY KEY (MaChiTietHoaDon),
	CONSTRAINT FK_ChiTietHoaDon_HoaDon FOREIGN KEY (MaHoaDon) REFERENCES HoaDon(MaHoaDon),
	CONSTRAINT FK_ChiTietHoaDon_Ve FOREIGN KEY (MaVe) REFERENCES Ve(MaVe)
)


CREATE TABLE LichSuTraVe (
	MaLichSuTraVe INT NOT NULL AUTO_INCREMENT,
	ThoiGianTraVe DATETIME NOT NULL DEFAULT CURRENT_TIME(),
	GhiChu VARCHAR(255) NULL,
	MaKhachHang INT NOT NULL,
	MaVe VARCHAR(25) NOT NULL,
	CONSTRAINT PK_LichSuTraVe PRIMARY KEY (MaLichSuTraVe),
	CONSTRAINT FK_LichSuTraVe_KhachHang FOREIGN KEY (MaKhachHang) REFERENCES KhachHang(MaKhachHang),
	CONSTRAINT FK_LichSuTraVe_Ve FOREIGN KEY (MaVe) REFERENCES Ve(MaVe)
)

CREATE TABLE TiepNhanYeuCauDoiVe (
	MaYeuCau INT NOT NULL AUTO_INCREMENT,
	ThoiGianTiepNhan DATETIME NOT NULL DEFAULT CURRENT_TIME(),
	ThoiGianYeuCauDoi DATETIME NOT NULL,
	GhiChu VARCHAR(255) NULL,
	MaKhachHang INT NOT NULL,
	MaNhanVien INT NOT NULL,
	CONSTRAINT PK_TiepNhanYeuCauDoiVe PRIMARY KEY (MaYeuCau),
	CONSTRAINT FK_TiepNhanYeuCauDoiVe_KhachHang FOREIGN KEY (MaKhachHang) REFERENCES KhachHang(MaKhachHang),
	CONSTRAINT FK_TiepNhanYeuCauDoiVe_NhanVien FOREIGN KEY (MaNhanVien) REFERENCES NhanVien(MaNhanVien)
)


