INSERT INTO quanlibanve.Khoang (MaKhoang,TenKhoang,MaToa,MaLoaiKhoang) VALUES
	 ('D10H-toa1-toa1-khoang-ghengoi','D10H Toa tàu 1Toa1 Khoang (Ghế ngồi)','D10H-toa1','ghe-ngoi'),
	 ('D10H-toa2-toa2-khoang-ghengoi','D10H Toa tàu 2Toa2 Khoang (Ghế ngồi)','D10H-toa2','ghe-ngoi'),
	 ('D10H-toa3-khoang1-giuongnamkhoang4','D10H Toa tàu 3 Khoang 1 (Giường nằm khoang 4)','D10H-toa3','giuong-nam-khoang-4'),
	 ('D10H-toa3-khoang2-giuongnamkhoang4','D10H Toa tàu 3 Khoang 2 (Giường nằm khoang 4)','D10H-toa3','giuong-nam-khoang-4'),
	 ('D10H-toa3-khoang3-giuongnamkhoang4','D10H Toa tàu 3 Khoang 3 (Giường nằm khoang 4)','D10H-toa3','giuong-nam-khoang-4'),
	 ('D10H-toa3-khoang4-giuongnamkhoang4','D10H Toa tàu 3 Khoang 4 (Giường nằm khoang 4)','D10H-toa3','giuong-nam-khoang-4'),
	 ('D10H-toa4-khoang1-giuongnamkhoang4','D10H Toa tàu 4 Khoang 1 (Giường nằm khoang 4)','D10H-toa4','giuong-nam-khoang-4'),
	 ('D10H-toa4-khoang2-giuongnamkhoang4','D10H Toa tàu 4 Khoang 2 (Giường nằm khoang 4)','D10H-toa4','giuong-nam-khoang-4'),
	 ('D10H-toa4-khoang3-giuongnamkhoang4','D10H Toa tàu 4 Khoang 3 (Giường nằm khoang 4)','D10H-toa4','giuong-nam-khoang-4'),
	 ('D10H-toa4-khoang4-giuongnamkhoang4','D10H Toa tàu 4 Khoang 4 (Giường nằm khoang 4)','D10H-toa4','giuong-nam-khoang-4');
INSERT INTO quanlibanve.Khoang (MaKhoang,TenKhoang,MaToa,MaLoaiKhoang) VALUES
	 ('D10H-toa5-khoang1-giuongnamkhoang6','D10H Toa tàu 5 Khoang 1 (Giường nằm khoang 6)','D10H-toa5','giuong-nam-khoang-6'),
	 ('D10H-toa5-khoang2-giuongnamkhoang6','D10H Toa tàu 5 Khoang 2 (Giường nằm khoang 6)','D10H-toa5','giuong-nam-khoang-6'),
	 ('D10H-toa5-khoang3-giuongnamkhoang6','D10H Toa tàu 5 Khoang 3 (Giường nằm khoang 6)','D10H-toa5','giuong-nam-khoang-6'),
	 ('D10H-toa5-khoang4-giuongnamkhoang6','D10H Toa tàu 5 Khoang 4 (Giường nằm khoang 6)','D10H-toa5','giuong-nam-khoang-6'),
	 ('D10H-toa6-khoang1-giuongnamkhoang6','D10H Toa tàu 6 Khoang 1 (Giường nằm khoang 6)','D10H-toa6','giuong-nam-khoang-6'),
	 ('D10H-toa6-khoang2-giuongnamkhoang6','D10H Toa tàu 6 Khoang 2 (Giường nằm khoang 6)','D10H-toa6','giuong-nam-khoang-6'),
	 ('D10H-toa6-khoang3-giuongnamkhoang6','D10H Toa tàu 6 Khoang 3 (Giường nằm khoang 6)','D10H-toa6','giuong-nam-khoang-6'),
	 ('D10H-toa6-khoang4-giuongnamkhoang6','D10H Toa tàu 6 Khoang 4 (Giường nằm khoang 6)','D10H-toa6','giuong-nam-khoang-6'),
	 ('D11H-toa1-toa1-khoang-ghengoi','D11H Toa tàu 1Toa1 Khoang (Ghế ngồi)','D11H-toa1','ghe-ngoi'),
	 ('D11H-toa2-toa2-khoang-ghengoi','D11H Toa tàu 2Toa2 Khoang (Ghế ngồi)','D11H-toa2','ghe-ngoi');
INSERT INTO quanlibanve.Khoang (MaKhoang,TenKhoang,MaToa,MaLoaiKhoang) VALUES
	 ('D11H-toa3-khoang1-giuongnamkhoang4','D11H Toa tàu 3 Khoang 1 (Giường nằm khoang 4)','D11H-toa3','giuong-nam-khoang-4'),
	 ('D11H-toa3-khoang2-giuongnamkhoang4','D11H Toa tàu 3 Khoang 2 (Giường nằm khoang 4)','D11H-toa3','giuong-nam-khoang-4'),
	 ('D11H-toa3-khoang3-giuongnamkhoang4','D11H Toa tàu 3 Khoang 3 (Giường nằm khoang 4)','D11H-toa3','giuong-nam-khoang-4'),
	 ('D11H-toa3-khoang4-giuongnamkhoang4','D11H Toa tàu 3 Khoang 4 (Giường nằm khoang 4)','D11H-toa3','giuong-nam-khoang-4'),
	 ('D11H-toa4-khoang1-giuongnamkhoang4','D11H Toa tàu 4 Khoang 1 (Giường nằm khoang 4)','D11H-toa4','giuong-nam-khoang-4'),
	 ('D11H-toa4-khoang2-giuongnamkhoang4','D11H Toa tàu 4 Khoang 2 (Giường nằm khoang 4)','D11H-toa4','giuong-nam-khoang-4'),
	 ('D11H-toa4-khoang3-giuongnamkhoang4','D11H Toa tàu 4 Khoang 3 (Giường nằm khoang 4)','D11H-toa4','giuong-nam-khoang-4'),
	 ('D11H-toa4-khoang4-giuongnamkhoang4','D11H Toa tàu 4 Khoang 4 (Giường nằm khoang 4)','D11H-toa4','giuong-nam-khoang-4'),
	 ('D11H-toa5-khoang1-giuongnamkhoang6','D11H Toa tàu 5 Khoang 1 (Giường nằm khoang 6)','D11H-toa5','giuong-nam-khoang-6'),
	 ('D11H-toa5-khoang2-giuongnamkhoang6','D11H Toa tàu 5 Khoang 2 (Giường nằm khoang 6)','D11H-toa5','giuong-nam-khoang-6');
INSERT INTO quanlibanve.Khoang (MaKhoang,TenKhoang,MaToa,MaLoaiKhoang) VALUES
	 ('D11H-toa5-khoang3-giuongnamkhoang6','D11H Toa tàu 5 Khoang 3 (Giường nằm khoang 6)','D11H-toa5','giuong-nam-khoang-6'),
	 ('D11H-toa5-khoang4-giuongnamkhoang6','D11H Toa tàu 5 Khoang 4 (Giường nằm khoang 6)','D11H-toa5','giuong-nam-khoang-6'),
	 ('D11H-toa6-khoang1-giuongnamkhoang6','D11H Toa tàu 6 Khoang 1 (Giường nằm khoang 6)','D11H-toa6','giuong-nam-khoang-6'),
	 ('D11H-toa6-khoang2-giuongnamkhoang6','D11H Toa tàu 6 Khoang 2 (Giường nằm khoang 6)','D11H-toa6','giuong-nam-khoang-6'),
	 ('D11H-toa6-khoang3-giuongnamkhoang6','D11H Toa tàu 6 Khoang 3 (Giường nằm khoang 6)','D11H-toa6','giuong-nam-khoang-6'),
	 ('D11H-toa6-khoang4-giuongnamkhoang6','D11H Toa tàu 6 Khoang 4 (Giường nằm khoang 6)','D11H-toa6','giuong-nam-khoang-6'),
	 ('D12E-toa1-toa1-khoang-ghengoi','D12E Toa tàu 1Toa1 Khoang (Ghế ngồi)','D12E-toa1','ghe-ngoi'),
	 ('D12E-toa2-toa2-khoang-ghengoi','D12E Toa tàu 2Toa2 Khoang (Ghế ngồi)','D12E-toa2','ghe-ngoi'),
	 ('D12E-toa3-khoang1-giuongnamkhoang4','D12E Toa tàu 3 Khoang 1 (Giường nằm khoang 4)','D12E-toa3','giuong-nam-khoang-4'),
	 ('D12E-toa3-khoang2-giuongnamkhoang4','D12E Toa tàu 3 Khoang 2 (Giường nằm khoang 4)','D12E-toa3','giuong-nam-khoang-4');
INSERT INTO quanlibanve.Khoang (MaKhoang,TenKhoang,MaToa,MaLoaiKhoang) VALUES
	 ('D12E-toa3-khoang3-giuongnamkhoang4','D12E Toa tàu 3 Khoang 3 (Giường nằm khoang 4)','D12E-toa3','giuong-nam-khoang-4'),
	 ('D12E-toa3-khoang4-giuongnamkhoang4','D12E Toa tàu 3 Khoang 4 (Giường nằm khoang 4)','D12E-toa3','giuong-nam-khoang-4'),
	 ('D12E-toa4-khoang1-giuongnamkhoang4','D12E Toa tàu 4 Khoang 1 (Giường nằm khoang 4)','D12E-toa4','giuong-nam-khoang-4'),
	 ('D12E-toa4-khoang2-giuongnamkhoang4','D12E Toa tàu 4 Khoang 2 (Giường nằm khoang 4)','D12E-toa4','giuong-nam-khoang-4'),
	 ('D12E-toa4-khoang3-giuongnamkhoang4','D12E Toa tàu 4 Khoang 3 (Giường nằm khoang 4)','D12E-toa4','giuong-nam-khoang-4'),
	 ('D12E-toa4-khoang4-giuongnamkhoang4','D12E Toa tàu 4 Khoang 4 (Giường nằm khoang 4)','D12E-toa4','giuong-nam-khoang-4'),
	 ('D12E-toa5-khoang1-giuongnamkhoang6','D12E Toa tàu 5 Khoang 1 (Giường nằm khoang 6)','D12E-toa5','giuong-nam-khoang-6'),
	 ('D12E-toa5-khoang2-giuongnamkhoang6','D12E Toa tàu 5 Khoang 2 (Giường nằm khoang 6)','D12E-toa5','giuong-nam-khoang-6'),
	 ('D12E-toa5-khoang3-giuongnamkhoang6','D12E Toa tàu 5 Khoang 3 (Giường nằm khoang 6)','D12E-toa5','giuong-nam-khoang-6'),
	 ('D12E-toa5-khoang4-giuongnamkhoang6','D12E Toa tàu 5 Khoang 4 (Giường nằm khoang 6)','D12E-toa5','giuong-nam-khoang-6');
INSERT INTO quanlibanve.Khoang (MaKhoang,TenKhoang,MaToa,MaLoaiKhoang) VALUES
	 ('D12E-toa6-khoang1-giuongnamkhoang6','D12E Toa tàu 6 Khoang 1 (Giường nằm khoang 6)','D12E-toa6','giuong-nam-khoang-6'),
	 ('D12E-toa6-khoang2-giuongnamkhoang6','D12E Toa tàu 6 Khoang 2 (Giường nằm khoang 6)','D12E-toa6','giuong-nam-khoang-6'),
	 ('D12E-toa6-khoang3-giuongnamkhoang6','D12E Toa tàu 6 Khoang 3 (Giường nằm khoang 6)','D12E-toa6','giuong-nam-khoang-6'),
	 ('D12E-toa6-khoang4-giuongnamkhoang6','D12E Toa tàu 6 Khoang 4 (Giường nằm khoang 6)','D12E-toa6','giuong-nam-khoang-6'),
	 ('D13E-toa1-toa1-khoang-ghengoi','D13E Toa tàu 1Toa1 Khoang (Ghế ngồi)','D13E-toa1','ghe-ngoi'),
	 ('D13E-toa2-toa2-khoang-ghengoi','D13E Toa tàu 2Toa2 Khoang (Ghế ngồi)','D13E-toa2','ghe-ngoi'),
	 ('D13E-toa3-khoang1-giuongnamkhoang4','D13E Toa tàu 3 Khoang 1 (Giường nằm khoang 4)','D13E-toa3','giuong-nam-khoang-4'),
	 ('D13E-toa3-khoang2-giuongnamkhoang4','D13E Toa tàu 3 Khoang 2 (Giường nằm khoang 4)','D13E-toa3','giuong-nam-khoang-4'),
	 ('D13E-toa3-khoang3-giuongnamkhoang4','D13E Toa tàu 3 Khoang 3 (Giường nằm khoang 4)','D13E-toa3','giuong-nam-khoang-4'),
	 ('D13E-toa3-khoang4-giuongnamkhoang4','D13E Toa tàu 3 Khoang 4 (Giường nằm khoang 4)','D13E-toa3','giuong-nam-khoang-4');
INSERT INTO quanlibanve.Khoang (MaKhoang,TenKhoang,MaToa,MaLoaiKhoang) VALUES
	 ('D13E-toa4-khoang1-giuongnamkhoang4','D13E Toa tàu 4 Khoang 1 (Giường nằm khoang 4)','D13E-toa4','giuong-nam-khoang-4'),
	 ('D13E-toa4-khoang2-giuongnamkhoang4','D13E Toa tàu 4 Khoang 2 (Giường nằm khoang 4)','D13E-toa4','giuong-nam-khoang-4'),
	 ('D13E-toa4-khoang3-giuongnamkhoang4','D13E Toa tàu 4 Khoang 3 (Giường nằm khoang 4)','D13E-toa4','giuong-nam-khoang-4'),
	 ('D13E-toa4-khoang4-giuongnamkhoang4','D13E Toa tàu 4 Khoang 4 (Giường nằm khoang 4)','D13E-toa4','giuong-nam-khoang-4'),
	 ('D13E-toa5-khoang1-giuongnamkhoang6','D13E Toa tàu 5 Khoang 1 (Giường nằm khoang 6)','D13E-toa5','giuong-nam-khoang-6'),
	 ('D13E-toa5-khoang2-giuongnamkhoang6','D13E Toa tàu 5 Khoang 2 (Giường nằm khoang 6)','D13E-toa5','giuong-nam-khoang-6'),
	 ('D13E-toa5-khoang3-giuongnamkhoang6','D13E Toa tàu 5 Khoang 3 (Giường nằm khoang 6)','D13E-toa5','giuong-nam-khoang-6'),
	 ('D13E-toa5-khoang4-giuongnamkhoang6','D13E Toa tàu 5 Khoang 4 (Giường nằm khoang 6)','D13E-toa5','giuong-nam-khoang-6'),
	 ('D13E-toa6-khoang1-giuongnamkhoang6','D13E Toa tàu 6 Khoang 1 (Giường nằm khoang 6)','D13E-toa6','giuong-nam-khoang-6'),
	 ('D13E-toa6-khoang2-giuongnamkhoang6','D13E Toa tàu 6 Khoang 2 (Giường nằm khoang 6)','D13E-toa6','giuong-nam-khoang-6');
INSERT INTO quanlibanve.Khoang (MaKhoang,TenKhoang,MaToa,MaLoaiKhoang) VALUES
	 ('D13E-toa6-khoang3-giuongnamkhoang6','D13E Toa tàu 6 Khoang 3 (Giường nằm khoang 6)','D13E-toa6','giuong-nam-khoang-6'),
	 ('D13E-toa6-khoang4-giuongnamkhoang6','D13E Toa tàu 6 Khoang 4 (Giường nằm khoang 6)','D13E-toa6','giuong-nam-khoang-6'),
	 ('D18E-toa1-toa1-khoang-ghengoi','D18E Toa tàu 1Toa1 Khoang (Ghế ngồi)','D18E-toa1','ghe-ngoi'),
	 ('D18E-toa2-toa2-khoang-ghengoi','D18E Toa tàu 2Toa2 Khoang (Ghế ngồi)','D18E-toa2','ghe-ngoi'),
	 ('D18E-toa3-khoang1-giuongnamkhoang4','D18E Toa tàu 3 Khoang 1 (Giường nằm khoang 4)','D18E-toa3','giuong-nam-khoang-4'),
	 ('D18E-toa3-khoang2-giuongnamkhoang4','D18E Toa tàu 3 Khoang 2 (Giường nằm khoang 4)','D18E-toa3','giuong-nam-khoang-4'),
	 ('D18E-toa3-khoang3-giuongnamkhoang4','D18E Toa tàu 3 Khoang 3 (Giường nằm khoang 4)','D18E-toa3','giuong-nam-khoang-4'),
	 ('D18E-toa3-khoang4-giuongnamkhoang4','D18E Toa tàu 3 Khoang 4 (Giường nằm khoang 4)','D18E-toa3','giuong-nam-khoang-4'),
	 ('D18E-toa4-khoang1-giuongnamkhoang4','D18E Toa tàu 4 Khoang 1 (Giường nằm khoang 4)','D18E-toa4','giuong-nam-khoang-4'),
	 ('D18E-toa4-khoang2-giuongnamkhoang4','D18E Toa tàu 4 Khoang 2 (Giường nằm khoang 4)','D18E-toa4','giuong-nam-khoang-4');
INSERT INTO quanlibanve.Khoang (MaKhoang,TenKhoang,MaToa,MaLoaiKhoang) VALUES
	 ('D18E-toa4-khoang3-giuongnamkhoang4','D18E Toa tàu 4 Khoang 3 (Giường nằm khoang 4)','D18E-toa4','giuong-nam-khoang-4'),
	 ('D18E-toa4-khoang4-giuongnamkhoang4','D18E Toa tàu 4 Khoang 4 (Giường nằm khoang 4)','D18E-toa4','giuong-nam-khoang-4'),
	 ('D18E-toa5-khoang1-giuongnamkhoang6','D18E Toa tàu 5 Khoang 1 (Giường nằm khoang 6)','D18E-toa5','giuong-nam-khoang-6'),
	 ('D18E-toa5-khoang2-giuongnamkhoang6','D18E Toa tàu 5 Khoang 2 (Giường nằm khoang 6)','D18E-toa5','giuong-nam-khoang-6'),
	 ('D18E-toa5-khoang3-giuongnamkhoang6','D18E Toa tàu 5 Khoang 3 (Giường nằm khoang 6)','D18E-toa5','giuong-nam-khoang-6'),
	 ('D18E-toa5-khoang4-giuongnamkhoang6','D18E Toa tàu 5 Khoang 4 (Giường nằm khoang 6)','D18E-toa5','giuong-nam-khoang-6'),
	 ('D18E-toa6-khoang1-giuongnamkhoang6','D18E Toa tàu 6 Khoang 1 (Giường nằm khoang 6)','D18E-toa6','giuong-nam-khoang-6'),
	 ('D18E-toa6-khoang2-giuongnamkhoang6','D18E Toa tàu 6 Khoang 2 (Giường nằm khoang 6)','D18E-toa6','giuong-nam-khoang-6'),
	 ('D18E-toa6-khoang3-giuongnamkhoang6','D18E Toa tàu 6 Khoang 3 (Giường nằm khoang 6)','D18E-toa6','giuong-nam-khoang-6'),
	 ('D18E-toa6-khoang4-giuongnamkhoang6','D18E Toa tàu 6 Khoang 4 (Giường nằm khoang 6)','D18E-toa6','giuong-nam-khoang-6');
INSERT INTO quanlibanve.Khoang (MaKhoang,TenKhoang,MaToa,MaLoaiKhoang) VALUES
	 ('D19E-toa1-toa1-khoang-ghengoi','D19E Toa tàu 1Toa1 Khoang (Ghế ngồi)','D19E-toa1','ghe-ngoi'),
	 ('D19E-toa2-toa2-khoang-ghengoi','D19E Toa tàu 2Toa2 Khoang (Ghế ngồi)','D19E-toa2','ghe-ngoi'),
	 ('D19E-toa3-khoang1-giuongnamkhoang4','D19E Toa tàu 3 Khoang 1 (Giường nằm khoang 4)','D19E-toa3','giuong-nam-khoang-4'),
	 ('D19E-toa3-khoang2-giuongnamkhoang4','D19E Toa tàu 3 Khoang 2 (Giường nằm khoang 4)','D19E-toa3','giuong-nam-khoang-4'),
	 ('D19E-toa3-khoang3-giuongnamkhoang4','D19E Toa tàu 3 Khoang 3 (Giường nằm khoang 4)','D19E-toa3','giuong-nam-khoang-4'),
	 ('D19E-toa3-khoang4-giuongnamkhoang4','D19E Toa tàu 3 Khoang 4 (Giường nằm khoang 4)','D19E-toa3','giuong-nam-khoang-4'),
	 ('D19E-toa4-khoang1-giuongnamkhoang4','D19E Toa tàu 4 Khoang 1 (Giường nằm khoang 4)','D19E-toa4','giuong-nam-khoang-4'),
	 ('D19E-toa4-khoang2-giuongnamkhoang4','D19E Toa tàu 4 Khoang 2 (Giường nằm khoang 4)','D19E-toa4','giuong-nam-khoang-4'),
	 ('D19E-toa4-khoang3-giuongnamkhoang4','D19E Toa tàu 4 Khoang 3 (Giường nằm khoang 4)','D19E-toa4','giuong-nam-khoang-4'),
	 ('D19E-toa4-khoang4-giuongnamkhoang4','D19E Toa tàu 4 Khoang 4 (Giường nằm khoang 4)','D19E-toa4','giuong-nam-khoang-4');
INSERT INTO quanlibanve.Khoang (MaKhoang,TenKhoang,MaToa,MaLoaiKhoang) VALUES
	 ('D19E-toa5-khoang1-giuongnamkhoang6','D19E Toa tàu 5 Khoang 1 (Giường nằm khoang 6)','D19E-toa5','giuong-nam-khoang-6'),
	 ('D19E-toa5-khoang2-giuongnamkhoang6','D19E Toa tàu 5 Khoang 2 (Giường nằm khoang 6)','D19E-toa5','giuong-nam-khoang-6'),
	 ('D19E-toa5-khoang3-giuongnamkhoang6','D19E Toa tàu 5 Khoang 3 (Giường nằm khoang 6)','D19E-toa5','giuong-nam-khoang-6'),
	 ('D19E-toa5-khoang4-giuongnamkhoang6','D19E Toa tàu 5 Khoang 4 (Giường nằm khoang 6)','D19E-toa5','giuong-nam-khoang-6'),
	 ('D19E-toa6-khoang1-giuongnamkhoang6','D19E Toa tàu 6 Khoang 1 (Giường nằm khoang 6)','D19E-toa6','giuong-nam-khoang-6'),
	 ('D19E-toa6-khoang2-giuongnamkhoang6','D19E Toa tàu 6 Khoang 2 (Giường nằm khoang 6)','D19E-toa6','giuong-nam-khoang-6'),
	 ('D19E-toa6-khoang3-giuongnamkhoang6','D19E Toa tàu 6 Khoang 3 (Giường nằm khoang 6)','D19E-toa6','giuong-nam-khoang-6'),
	 ('D19E-toa6-khoang4-giuongnamkhoang6','D19E Toa tàu 6 Khoang 4 (Giường nằm khoang 6)','D19E-toa6','giuong-nam-khoang-6'),
	 ('D20E-toa1-toa1-khoang-ghengoi','D20E Toa tàu 1Toa1 Khoang (Ghế ngồi)','D20E-toa1','ghe-ngoi'),
	 ('D20E-toa2-toa2-khoang-ghengoi','D20E Toa tàu 2Toa2 Khoang (Ghế ngồi)','D20E-toa2','ghe-ngoi');
INSERT INTO quanlibanve.Khoang (MaKhoang,TenKhoang,MaToa,MaLoaiKhoang) VALUES
	 ('D20E-toa3-khoang1-giuongnamkhoang4','D20E Toa tàu 3 Khoang 1 (Giường nằm khoang 4)','D20E-toa3','giuong-nam-khoang-4'),
	 ('D20E-toa3-khoang2-giuongnamkhoang4','D20E Toa tàu 3 Khoang 2 (Giường nằm khoang 4)','D20E-toa3','giuong-nam-khoang-4'),
	 ('D20E-toa3-khoang3-giuongnamkhoang4','D20E Toa tàu 3 Khoang 3 (Giường nằm khoang 4)','D20E-toa3','giuong-nam-khoang-4'),
	 ('D20E-toa3-khoang4-giuongnamkhoang4','D20E Toa tàu 3 Khoang 4 (Giường nằm khoang 4)','D20E-toa3','giuong-nam-khoang-4'),
	 ('D20E-toa4-khoang1-giuongnamkhoang4','D20E Toa tàu 4 Khoang 1 (Giường nằm khoang 4)','D20E-toa4','giuong-nam-khoang-4'),
	 ('D20E-toa4-khoang2-giuongnamkhoang4','D20E Toa tàu 4 Khoang 2 (Giường nằm khoang 4)','D20E-toa4','giuong-nam-khoang-4'),
	 ('D20E-toa4-khoang3-giuongnamkhoang4','D20E Toa tàu 4 Khoang 3 (Giường nằm khoang 4)','D20E-toa4','giuong-nam-khoang-4'),
	 ('D20E-toa4-khoang4-giuongnamkhoang4','D20E Toa tàu 4 Khoang 4 (Giường nằm khoang 4)','D20E-toa4','giuong-nam-khoang-4'),
	 ('D20E-toa5-khoang1-giuongnamkhoang6','D20E Toa tàu 5 Khoang 1 (Giường nằm khoang 6)','D20E-toa5','giuong-nam-khoang-6'),
	 ('D20E-toa5-khoang2-giuongnamkhoang6','D20E Toa tàu 5 Khoang 2 (Giường nằm khoang 6)','D20E-toa5','giuong-nam-khoang-6');
INSERT INTO quanlibanve.Khoang (MaKhoang,TenKhoang,MaToa,MaLoaiKhoang) VALUES
	 ('D20E-toa5-khoang3-giuongnamkhoang6','D20E Toa tàu 5 Khoang 3 (Giường nằm khoang 6)','D20E-toa5','giuong-nam-khoang-6'),
	 ('D20E-toa5-khoang4-giuongnamkhoang6','D20E Toa tàu 5 Khoang 4 (Giường nằm khoang 6)','D20E-toa5','giuong-nam-khoang-6'),
	 ('D20E-toa6-khoang1-giuongnamkhoang6','D20E Toa tàu 6 Khoang 1 (Giường nằm khoang 6)','D20E-toa6','giuong-nam-khoang-6'),
	 ('D20E-toa6-khoang2-giuongnamkhoang6','D20E Toa tàu 6 Khoang 2 (Giường nằm khoang 6)','D20E-toa6','giuong-nam-khoang-6'),
	 ('D20E-toa6-khoang3-giuongnamkhoang6','D20E Toa tàu 6 Khoang 3 (Giường nằm khoang 6)','D20E-toa6','giuong-nam-khoang-6'),
	 ('D20E-toa6-khoang4-giuongnamkhoang6','D20E Toa tàu 6 Khoang 4 (Giường nằm khoang 6)','D20E-toa6','giuong-nam-khoang-6'),
	 ('D4H-toa1-toa1-khoang-ghengoi','D4H Toa tàu 1Toa1 Khoang (Ghế ngồi)','D4H-toa1','ghe-ngoi'),
	 ('D4H-toa2-toa2-khoang-ghengoi','D4H Toa tàu 2Toa2 Khoang (Ghế ngồi)','D4H-toa2','ghe-ngoi'),
	 ('D4H-toa3-khoang1-giuongnamkhoang4','D4H Toa tàu 3 Khoang 1 (Giường nằm khoang 4)','D4H-toa3','giuong-nam-khoang-4'),
	 ('D4H-toa3-khoang2-giuongnamkhoang4','D4H Toa tàu 3 Khoang 2 (Giường nằm khoang 4)','D4H-toa3','giuong-nam-khoang-4');
INSERT INTO quanlibanve.Khoang (MaKhoang,TenKhoang,MaToa,MaLoaiKhoang) VALUES
	 ('D4H-toa3-khoang3-giuongnamkhoang4','D4H Toa tàu 3 Khoang 3 (Giường nằm khoang 4)','D4H-toa3','giuong-nam-khoang-4'),
	 ('D4H-toa3-khoang4-giuongnamkhoang4','D4H Toa tàu 3 Khoang 4 (Giường nằm khoang 4)','D4H-toa3','giuong-nam-khoang-4'),
	 ('D4H-toa4-khoang1-giuongnamkhoang4','D4H Toa tàu 4 Khoang 1 (Giường nằm khoang 4)','D4H-toa4','giuong-nam-khoang-4'),
	 ('D4H-toa4-khoang2-giuongnamkhoang4','D4H Toa tàu 4 Khoang 2 (Giường nằm khoang 4)','D4H-toa4','giuong-nam-khoang-4'),
	 ('D4H-toa4-khoang3-giuongnamkhoang4','D4H Toa tàu 4 Khoang 3 (Giường nằm khoang 4)','D4H-toa4','giuong-nam-khoang-4'),
	 ('D4H-toa4-khoang4-giuongnamkhoang4','D4H Toa tàu 4 Khoang 4 (Giường nằm khoang 4)','D4H-toa4','giuong-nam-khoang-4'),
	 ('D4H-toa5-khoang1-giuongnamkhoang6','D4H Toa tàu 5 Khoang 1 (Giường nằm khoang 6)','D4H-toa5','giuong-nam-khoang-6'),
	 ('D4H-toa5-khoang2-giuongnamkhoang6','D4H Toa tàu 5 Khoang 2 (Giường nằm khoang 6)','D4H-toa5','giuong-nam-khoang-6'),
	 ('D4H-toa5-khoang3-giuongnamkhoang6','D4H Toa tàu 5 Khoang 3 (Giường nằm khoang 6)','D4H-toa5','giuong-nam-khoang-6'),
	 ('D4H-toa5-khoang4-giuongnamkhoang6','D4H Toa tàu 5 Khoang 4 (Giường nằm khoang 6)','D4H-toa5','giuong-nam-khoang-6');
INSERT INTO quanlibanve.Khoang (MaKhoang,TenKhoang,MaToa,MaLoaiKhoang) VALUES
	 ('D4H-toa6-khoang1-giuongnamkhoang6','D4H Toa tàu 6 Khoang 1 (Giường nằm khoang 6)','D4H-toa6','giuong-nam-khoang-6'),
	 ('D4H-toa6-khoang2-giuongnamkhoang6','D4H Toa tàu 6 Khoang 2 (Giường nằm khoang 6)','D4H-toa6','giuong-nam-khoang-6'),
	 ('D4H-toa6-khoang3-giuongnamkhoang6','D4H Toa tàu 6 Khoang 3 (Giường nằm khoang 6)','D4H-toa6','giuong-nam-khoang-6'),
	 ('D4H-toa6-khoang4-giuongnamkhoang6','D4H Toa tàu 6 Khoang 4 (Giường nằm khoang 6)','D4H-toa6','giuong-nam-khoang-6'),
	 ('D5H-toa1-toa1-khoang-ghengoi','D5H Toa tàu 1Toa1 Khoang (Ghế ngồi)','D5H-toa1','ghe-ngoi'),
	 ('D5H-toa2-toa2-khoang-ghengoi','D5H Toa tàu 2Toa2 Khoang (Ghế ngồi)','D5H-toa2','ghe-ngoi'),
	 ('D5H-toa3-khoang1-giuongnamkhoang4','D5H Toa tàu 3 Khoang 1 (Giường nằm khoang 4)','D5H-toa3','giuong-nam-khoang-4'),
	 ('D5H-toa3-khoang2-giuongnamkhoang4','D5H Toa tàu 3 Khoang 2 (Giường nằm khoang 4)','D5H-toa3','giuong-nam-khoang-4'),
	 ('D5H-toa3-khoang3-giuongnamkhoang4','D5H Toa tàu 3 Khoang 3 (Giường nằm khoang 4)','D5H-toa3','giuong-nam-khoang-4'),
	 ('D5H-toa3-khoang4-giuongnamkhoang4','D5H Toa tàu 3 Khoang 4 (Giường nằm khoang 4)','D5H-toa3','giuong-nam-khoang-4');
INSERT INTO quanlibanve.Khoang (MaKhoang,TenKhoang,MaToa,MaLoaiKhoang) VALUES
	 ('D5H-toa4-khoang1-giuongnamkhoang4','D5H Toa tàu 4 Khoang 1 (Giường nằm khoang 4)','D5H-toa4','giuong-nam-khoang-4'),
	 ('D5H-toa4-khoang2-giuongnamkhoang4','D5H Toa tàu 4 Khoang 2 (Giường nằm khoang 4)','D5H-toa4','giuong-nam-khoang-4'),
	 ('D5H-toa4-khoang3-giuongnamkhoang4','D5H Toa tàu 4 Khoang 3 (Giường nằm khoang 4)','D5H-toa4','giuong-nam-khoang-4'),
	 ('D5H-toa4-khoang4-giuongnamkhoang4','D5H Toa tàu 4 Khoang 4 (Giường nằm khoang 4)','D5H-toa4','giuong-nam-khoang-4'),
	 ('D5H-toa5-khoang1-giuongnamkhoang6','D5H Toa tàu 5 Khoang 1 (Giường nằm khoang 6)','D5H-toa5','giuong-nam-khoang-6'),
	 ('D5H-toa5-khoang2-giuongnamkhoang6','D5H Toa tàu 5 Khoang 2 (Giường nằm khoang 6)','D5H-toa5','giuong-nam-khoang-6'),
	 ('D5H-toa5-khoang3-giuongnamkhoang6','D5H Toa tàu 5 Khoang 3 (Giường nằm khoang 6)','D5H-toa5','giuong-nam-khoang-6'),
	 ('D5H-toa5-khoang4-giuongnamkhoang6','D5H Toa tàu 5 Khoang 4 (Giường nằm khoang 6)','D5H-toa5','giuong-nam-khoang-6'),
	 ('D5H-toa6-khoang1-giuongnamkhoang6','D5H Toa tàu 6 Khoang 1 (Giường nằm khoang 6)','D5H-toa6','giuong-nam-khoang-6'),
	 ('D5H-toa6-khoang2-giuongnamkhoang6','D5H Toa tàu 6 Khoang 2 (Giường nằm khoang 6)','D5H-toa6','giuong-nam-khoang-6');
INSERT INTO quanlibanve.Khoang (MaKhoang,TenKhoang,MaToa,MaLoaiKhoang) VALUES
	 ('D5H-toa6-khoang3-giuongnamkhoang6','D5H Toa tàu 6 Khoang 3 (Giường nằm khoang 6)','D5H-toa6','giuong-nam-khoang-6'),
	 ('D5H-toa6-khoang4-giuongnamkhoang6','D5H Toa tàu 6 Khoang 4 (Giường nằm khoang 6)','D5H-toa6','giuong-nam-khoang-6'),
	 ('D8E-toa1-toa1-khoang-ghengoi','D8E Toa tàu 1Toa1 Khoang (Ghế ngồi)','D8E-toa1','ghe-ngoi'),
	 ('D8E-toa2-toa2-khoang-ghengoi','D8E Toa tàu 2Toa2 Khoang (Ghế ngồi)','D8E-toa2','ghe-ngoi'),
	 ('D8E-toa3-khoang1-giuongnamkhoang4','D8E Toa tàu 3 Khoang 1 (Giường nằm khoang 4)','D8E-toa3','giuong-nam-khoang-4'),
	 ('D8E-toa3-khoang2-giuongnamkhoang4','D8E Toa tàu 3 Khoang 2 (Giường nằm khoang 4)','D8E-toa3','giuong-nam-khoang-4'),
	 ('D8E-toa3-khoang3-giuongnamkhoang4','D8E Toa tàu 3 Khoang 3 (Giường nằm khoang 4)','D8E-toa3','giuong-nam-khoang-4'),
	 ('D8E-toa3-khoang4-giuongnamkhoang4','D8E Toa tàu 3 Khoang 4 (Giường nằm khoang 4)','D8E-toa3','giuong-nam-khoang-4'),
	 ('D8E-toa4-khoang1-giuongnamkhoang4','D8E Toa tàu 4 Khoang 1 (Giường nằm khoang 4)','D8E-toa4','giuong-nam-khoang-4'),
	 ('D8E-toa4-khoang2-giuongnamkhoang4','D8E Toa tàu 4 Khoang 2 (Giường nằm khoang 4)','D8E-toa4','giuong-nam-khoang-4');
INSERT INTO quanlibanve.Khoang (MaKhoang,TenKhoang,MaToa,MaLoaiKhoang) VALUES
	 ('D8E-toa4-khoang3-giuongnamkhoang4','D8E Toa tàu 4 Khoang 3 (Giường nằm khoang 4)','D8E-toa4','giuong-nam-khoang-4'),
	 ('D8E-toa4-khoang4-giuongnamkhoang4','D8E Toa tàu 4 Khoang 4 (Giường nằm khoang 4)','D8E-toa4','giuong-nam-khoang-4'),
	 ('D8E-toa5-khoang1-giuongnamkhoang6','D8E Toa tàu 5 Khoang 1 (Giường nằm khoang 6)','D8E-toa5','giuong-nam-khoang-6'),
	 ('D8E-toa5-khoang2-giuongnamkhoang6','D8E Toa tàu 5 Khoang 2 (Giường nằm khoang 6)','D8E-toa5','giuong-nam-khoang-6'),
	 ('D8E-toa5-khoang3-giuongnamkhoang6','D8E Toa tàu 5 Khoang 3 (Giường nằm khoang 6)','D8E-toa5','giuong-nam-khoang-6'),
	 ('D8E-toa5-khoang4-giuongnamkhoang6','D8E Toa tàu 5 Khoang 4 (Giường nằm khoang 6)','D8E-toa5','giuong-nam-khoang-6'),
	 ('D8E-toa6-khoang1-giuongnamkhoang6','D8E Toa tàu 6 Khoang 1 (Giường nằm khoang 6)','D8E-toa6','giuong-nam-khoang-6'),
	 ('D8E-toa6-khoang2-giuongnamkhoang6','D8E Toa tàu 6 Khoang 2 (Giường nằm khoang 6)','D8E-toa6','giuong-nam-khoang-6'),
	 ('D8E-toa6-khoang3-giuongnamkhoang6','D8E Toa tàu 6 Khoang 3 (Giường nằm khoang 6)','D8E-toa6','giuong-nam-khoang-6'),
	 ('D8E-toa6-khoang4-giuongnamkhoang6','D8E Toa tàu 6 Khoang 4 (Giường nằm khoang 6)','D8E-toa6','giuong-nam-khoang-6');
INSERT INTO quanlibanve.Khoang (MaKhoang,TenKhoang,MaToa,MaLoaiKhoang) VALUES
	 ('D9E-toa1-toa1-khoang-ghengoi','D9E Toa tàu 1Toa1 Khoang (Ghế ngồi)','D9E-toa1','ghe-ngoi'),
	 ('D9E-toa2-toa2-khoang-ghengoi','D9E Toa tàu 2Toa2 Khoang (Ghế ngồi)','D9E-toa2','ghe-ngoi'),
	 ('D9E-toa3-khoang1-giuongnamkhoang4','D9E Toa tàu 3 Khoang 1 (Giường nằm khoang 4)','D9E-toa3','giuong-nam-khoang-4'),
	 ('D9E-toa3-khoang2-giuongnamkhoang4','D9E Toa tàu 3 Khoang 2 (Giường nằm khoang 4)','D9E-toa3','giuong-nam-khoang-4'),
	 ('D9E-toa3-khoang3-giuongnamkhoang4','D9E Toa tàu 3 Khoang 3 (Giường nằm khoang 4)','D9E-toa3','giuong-nam-khoang-4'),
	 ('D9E-toa3-khoang4-giuongnamkhoang4','D9E Toa tàu 3 Khoang 4 (Giường nằm khoang 4)','D9E-toa3','giuong-nam-khoang-4'),
	 ('D9E-toa4-khoang1-giuongnamkhoang4','D9E Toa tàu 4 Khoang 1 (Giường nằm khoang 4)','D9E-toa4','giuong-nam-khoang-4'),
	 ('D9E-toa4-khoang2-giuongnamkhoang4','D9E Toa tàu 4 Khoang 2 (Giường nằm khoang 4)','D9E-toa4','giuong-nam-khoang-4'),
	 ('D9E-toa4-khoang3-giuongnamkhoang4','D9E Toa tàu 4 Khoang 3 (Giường nằm khoang 4)','D9E-toa4','giuong-nam-khoang-4'),
	 ('D9E-toa4-khoang4-giuongnamkhoang4','D9E Toa tàu 4 Khoang 4 (Giường nằm khoang 4)','D9E-toa4','giuong-nam-khoang-4');
INSERT INTO quanlibanve.Khoang (MaKhoang,TenKhoang,MaToa,MaLoaiKhoang) VALUES
	 ('D9E-toa5-khoang1-giuongnamkhoang6','D9E Toa tàu 5 Khoang 1 (Giường nằm khoang 6)','D9E-toa5','giuong-nam-khoang-6'),
	 ('D9E-toa5-khoang2-giuongnamkhoang6','D9E Toa tàu 5 Khoang 2 (Giường nằm khoang 6)','D9E-toa5','giuong-nam-khoang-6'),
	 ('D9E-toa5-khoang3-giuongnamkhoang6','D9E Toa tàu 5 Khoang 3 (Giường nằm khoang 6)','D9E-toa5','giuong-nam-khoang-6'),
	 ('D9E-toa5-khoang4-giuongnamkhoang6','D9E Toa tàu 5 Khoang 4 (Giường nằm khoang 6)','D9E-toa5','giuong-nam-khoang-6'),
	 ('D9E-toa6-khoang1-giuongnamkhoang6','D9E Toa tàu 6 Khoang 1 (Giường nằm khoang 6)','D9E-toa6','giuong-nam-khoang-6'),
	 ('D9E-toa6-khoang2-giuongnamkhoang6','D9E Toa tàu 6 Khoang 2 (Giường nằm khoang 6)','D9E-toa6','giuong-nam-khoang-6'),
	 ('D9E-toa6-khoang3-giuongnamkhoang6','D9E Toa tàu 6 Khoang 3 (Giường nằm khoang 6)','D9E-toa6','giuong-nam-khoang-6'),
	 ('D9E-toa6-khoang4-giuongnamkhoang6','D9E Toa tàu 6 Khoang 4 (Giường nằm khoang 6)','D9E-toa6','giuong-nam-khoang-6'),
	 ('D9E/D10E-toa1-toa1-khoang-ghengoi','D9E/D10E Toa tàu 1Toa1 Khoang (Ghế ngồi)','D9E/D10E-toa1','ghe-ngoi'),
	 ('D9E/D10E-toa2-toa2-khoang-ghengoi','D9E/D10E Toa tàu 2Toa2 Khoang (Ghế ngồi)','D9E/D10E-toa2','ghe-ngoi');
INSERT INTO quanlibanve.Khoang (MaKhoang,TenKhoang,MaToa,MaLoaiKhoang) VALUES
	 ('D9E/D10E-toa3-khoang1-giuongnamkhoang4','D9E/D10E Toa tàu 3 Khoang 1 (Giường nằm khoang 4)','D9E/D10E-toa3','giuong-nam-khoang-4'),
	 ('D9E/D10E-toa3-khoang2-giuongnamkhoang4','D9E/D10E Toa tàu 3 Khoang 2 (Giường nằm khoang 4)','D9E/D10E-toa3','giuong-nam-khoang-4'),
	 ('D9E/D10E-toa3-khoang3-giuongnamkhoang4','D9E/D10E Toa tàu 3 Khoang 3 (Giường nằm khoang 4)','D9E/D10E-toa3','giuong-nam-khoang-4'),
	 ('D9E/D10E-toa3-khoang4-giuongnamkhoang4','D9E/D10E Toa tàu 3 Khoang 4 (Giường nằm khoang 4)','D9E/D10E-toa3','giuong-nam-khoang-4'),
	 ('D9E/D10E-toa4-khoang1-giuongnamkhoang4','D9E/D10E Toa tàu 4 Khoang 1 (Giường nằm khoang 4)','D9E/D10E-toa4','giuong-nam-khoang-4'),
	 ('D9E/D10E-toa4-khoang2-giuongnamkhoang4','D9E/D10E Toa tàu 4 Khoang 2 (Giường nằm khoang 4)','D9E/D10E-toa4','giuong-nam-khoang-4'),
	 ('D9E/D10E-toa4-khoang3-giuongnamkhoang4','D9E/D10E Toa tàu 4 Khoang 3 (Giường nằm khoang 4)','D9E/D10E-toa4','giuong-nam-khoang-4'),
	 ('D9E/D10E-toa4-khoang4-giuongnamkhoang4','D9E/D10E Toa tàu 4 Khoang 4 (Giường nằm khoang 4)','D9E/D10E-toa4','giuong-nam-khoang-4'),
	 ('D9E/D10E-toa5-khoang1-giuongnamkhoang6','D9E/D10E Toa tàu 5 Khoang 1 (Giường nằm khoang 6)','D9E/D10E-toa5','giuong-nam-khoang-6'),
	 ('D9E/D10E-toa5-khoang2-giuongnamkhoang6','D9E/D10E Toa tàu 5 Khoang 2 (Giường nằm khoang 6)','D9E/D10E-toa5','giuong-nam-khoang-6');
INSERT INTO quanlibanve.Khoang (MaKhoang,TenKhoang,MaToa,MaLoaiKhoang) VALUES
	 ('D9E/D10E-toa5-khoang3-giuongnamkhoang6','D9E/D10E Toa tàu 5 Khoang 3 (Giường nằm khoang 6)','D9E/D10E-toa5','giuong-nam-khoang-6'),
	 ('D9E/D10E-toa5-khoang4-giuongnamkhoang6','D9E/D10E Toa tàu 5 Khoang 4 (Giường nằm khoang 6)','D9E/D10E-toa5','giuong-nam-khoang-6'),
	 ('D9E/D10E-toa6-khoang1-giuongnamkhoang6','D9E/D10E Toa tàu 6 Khoang 1 (Giường nằm khoang 6)','D9E/D10E-toa6','giuong-nam-khoang-6'),
	 ('D9E/D10E-toa6-khoang2-giuongnamkhoang6','D9E/D10E Toa tàu 6 Khoang 2 (Giường nằm khoang 6)','D9E/D10E-toa6','giuong-nam-khoang-6'),
	 ('D9E/D10E-toa6-khoang3-giuongnamkhoang6','D9E/D10E Toa tàu 6 Khoang 3 (Giường nằm khoang 6)','D9E/D10E-toa6','giuong-nam-khoang-6'),
	 ('D9E/D10E-toa6-khoang4-giuongnamkhoang6','D9E/D10E Toa tàu 6 Khoang 4 (Giường nằm khoang 6)','D9E/D10E-toa6','giuong-nam-khoang-6');
